FROM ubuntu:16.04
COPY proxy /proxy
COPY proxy/ssh /root/.ssh

RUN apt-get update -qq &&\
    apt-get install -qq --no-install-recommends polipo shadowsocks ssh &&\
    echo "==> Clean up..."  &&\   
	rm -rf /var/lib/apt/lists/*     &&\
    chmod +x /proxy/start_proxy.sh  && \
    chmod 0600 ~/.ssh/id_rsa*

CMD ["/proxy/start_proxy.sh"]
